apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: kubehello
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: kubehello
    template:
      metadata:
        labels:
          app: kubehello
      spec:
        containers:
          - name: mainApp
            image: kubehello:latest
            ports:
              - containerPort: 8080
            env:
              SERVER_PORT: "8080"
              SERVER_HOST: "0.0.0.0"