apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: kubehello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubehello
  template:
    metadata:
      labels:
        app: kubehello
    spec:
      containers:
        - name: main-app
          image: IMAGE_NAME_PLACEHOLDER
          ports:
            - containerPort: PORT_PLACEHOLDER
          env:
            - name: SERVER_PORT
              value: "PORT_PLACEHOLDER"
            - name: SERVER_HOST
              value: "0.0.0.0"